### ISSUE TITLE
Issue. Not sure its related to your stuff but i cant get it to run.

### ISSUE THREAD

**Issue by Zand3rsCode** [Mirasaki/cftools-bans-webhook-replacer#1]
SyntaxError: C:\GameServers\BanHook\config.json: Unexpected string in JSON at position 302
    at parse (<anonymous>)
    at Module._extensions..json (node:internal/modules/cjs/loader:1322:39)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\GameServers\BanHook\cftClient.js:10:5)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)

**Comment by Ariastarcos** [comment]
Your config.json file at `C:\GameServers\BanHook\config.json` has a syntax error

**Comment by Ariastarcos** [comment]
It's incorrect JSON

**Comment by Zand3rsCode** [comment]
Yes, it was a issue on my side. Still having some issue with it posting tho, but its me not understanding your description fully.
Thank you for your reply and help.

**Comment by Zand3rsCode** [comment]
Ok been trying to figure this out. I always get username Survivor. it wont grab the name. Any tips?

**Comment by Ariastarcos** [comment]
That means the ign can't be resolved from the CFTools servers you've provided

**Comment by Zand3rsCode** [comment]
Yes i understand but its like 20 bans that all come up as survivor and they all have a name if u put their id in the search box on cfcloud. SOrry to be persistent but i am just trying to understand :)

**Comment by Ariastarcos** [comment]
You might be getting rate-limited by CFTools. Hard to tell without seeing the logs

**Comment by Ariastarcos** [comment]
@Zand3rsCode Can you upload the logs for the application?

**Comment by Zand3rsCode** [comment]
SyntaxError: C:\GameServers\BanHook\config.json: Unexpected token / in JSON at position 902
    at parse (<anonymous>)
    at Module._extensions..json (node:internal/modules/cjs/loader:1322:39)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at Hook._require.Module.require (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\require-in-the-middle\index.js:101:39)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\GameServers\BanHook\cftClient.js:10:5)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)

Yeah clearly i have an error somewhere in my config but its nothing obvious and visual code doesent hint it either,
I will redo the config from scratch one more time and try it.

**Comment by Zand3rsCode** [comment]
No error, no logs anywhere still not working i give up :)

**Comment by Ariastarcos** [comment]
You could have just shared the config with your credentials replaced with something incorrect.
