### ISSUE TITLE
Issue with fetching data

### ISSUE THREAD

**Issue by mr190e** [Mirasaki/cftools-bans-webhook-replacer#2]
When runnign the bot it gives me this error in the console:

```
Error encounter fetching player information
ReferenceError: fetch is not defined
    at fetchPlayerDetails (/root/CF_NicerBans/cftools-bans-webhook-replacer/cftClient.js:50:5)
    at tryPlayerName (/root/CF_NicerBans/cftools-bans-webhook-replacer/cftClient.js:75:23)
    at Client.<anonymous> (/root/CF_NicerBans/cftools-bans-webhook-replacer/index.js:77:23)
    at Client.emit (node:events:513:28)
    at MessageCreateAction.handle (/root/CF_NicerBans/cftools-bans-webhook-replacer/node_modules/discord.js/src/client/actions/MessageCreate.js:28:14)
    at Object.module.exports [as MESSAGE_CREATE] (/root/CF_NicerBans/cftools-bans-webhook-replacer/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/root/CF_NicerBans/cftools-bans-webhook-replacer/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (/root/CF_NicerBans/cftools-bans-webhook-replacer/node_modules/discord.js/src/client/websocket/WebSocketShard.js:489:22)
    at WebSocketShard.onMessage (/root/CF_NicerBans/cftools-bans-webhook-replacer/node_modules/discord.js/src/client/websocket/WebSocketShard.js:328:10)
    at callListener (/root/CF_NicerBans/cftools-bans-webhook-replacer/node_modules/ws/lib/event-target.js:290:14)
Error encounter fetching player information
ReferenceError: fetch is not defined
    at fetchPlayerDetails (/root/CF_NicerBans/cftools-bans-webhook-replacer/cftClient.js:50:5)
    at tryPlayerName (/root/CF_NicerBans/cftools-bans-webhook-replacer/cftClient.js:75:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at
```

I run the bot on ubuntu 22.04

**Comment by Ariastarcos** [comment]
Updating your Node to LTS will fix this

**Comment by mr190e** [comment]
thanks for the quick reply. With NodeJS 18 LTS it works fine
